// Auto-generated by frontend/bundle.js — do not edit
// Run: cd frontend && npm run build && node bundle.js

pub const static_files = .{
    .{ "/_app/immutable/assets/0.yjmRQJU2.css", "text/css", "src/static/_app/immutable/assets/0.yjmRQJU2.css", @embedFile("static/_app/immutable/assets/0.yjmRQJU2.css") },
    .{ "/_app/immutable/assets/2.oqd7DzrZ.css", "text/css", "src/static/_app/immutable/assets/2.oqd7DzrZ.css", @embedFile("static/_app/immutable/assets/2.oqd7DzrZ.css") },
    .{ "/_app/immutable/chunks/BKz7k-_v.js", "application/javascript", "src/static/_app/immutable/chunks/BKz7k-_v.js", @embedFile("static/_app/immutable/chunks/BKz7k-_v.js") },
    .{ "/_app/immutable/chunks/BqkzyG10.js", "application/javascript", "src/static/_app/immutable/chunks/BqkzyG10.js", @embedFile("static/_app/immutable/chunks/BqkzyG10.js") },
    .{ "/_app/immutable/chunks/CZZbR7zT.js", "application/javascript", "src/static/_app/immutable/chunks/CZZbR7zT.js", @embedFile("static/_app/immutable/chunks/CZZbR7zT.js") },
    .{ "/_app/immutable/chunks/DBCBmo8Y.js", "application/javascript", "src/static/_app/immutable/chunks/DBCBmo8Y.js", @embedFile("static/_app/immutable/chunks/DBCBmo8Y.js") },
    .{ "/_app/immutable/chunks/DelolVe1.js", "application/javascript", "src/static/_app/immutable/chunks/DelolVe1.js", @embedFile("static/_app/immutable/chunks/DelolVe1.js") },
    .{ "/_app/immutable/chunks/wbPk3Yxo.js", "application/javascript", "src/static/_app/immutable/chunks/wbPk3Yxo.js", @embedFile("static/_app/immutable/chunks/wbPk3Yxo.js") },
    .{ "/_app/immutable/entry/app.DRzUdWli.js", "application/javascript", "src/static/_app/immutable/entry/app.DRzUdWli.js", @embedFile("static/_app/immutable/entry/app.DRzUdWli.js") },
    .{ "/_app/immutable/entry/start.BFc5w_m9.js", "application/javascript", "src/static/_app/immutable/entry/start.BFc5w_m9.js", @embedFile("static/_app/immutable/entry/start.BFc5w_m9.js") },
    .{ "/_app/immutable/nodes/0.NjZ0Ac80.js", "application/javascript", "src/static/_app/immutable/nodes/0.NjZ0Ac80.js", @embedFile("static/_app/immutable/nodes/0.NjZ0Ac80.js") },
    .{ "/_app/immutable/nodes/1.DeX2KZHG.js", "application/javascript", "src/static/_app/immutable/nodes/1.DeX2KZHG.js", @embedFile("static/_app/immutable/nodes/1.DeX2KZHG.js") },
    .{ "/_app/immutable/nodes/2.BXSVpWKd.js", "application/javascript", "src/static/_app/immutable/nodes/2.BXSVpWKd.js", @embedFile("static/_app/immutable/nodes/2.BXSVpWKd.js") },
    .{ "/_app/version.json", "application/json", "src/static/_app/version.json", @embedFile("static/_app/version.json") },
};
